### ISSUE TITLE
ERROR: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by sorgoz** [Illumina/Nirvana#115]
Stack trace:

```
Stack trace:
   at Nirvana.PreLoadUtilities.GetPositions(Stream vcfStream, GenomicRange genomicRange, ISequenceProvider sequenceProvider, IRefMinorProvider refMinorProvider) in /home/sergey/Nirvana-3.19/Nirvana/PreLoadUtilities.cs:line 16
   at Nirvana.AnnotationResources.GetVariantPositions(Stream vcfStream, GenomicRange genomicRange) in /home/sergey/Nirvana-3.19/Nirvana/AnnotationResources.cs:line 139
   at Nirvana.Nirvana.GetAnnotationResources() in /home/sergey/Nirvana-3.19/Nirvana/Nirvana.cs:line 67
   at Nirvana.Nirvana.ProgramExecution() in /home/sergey/Nirvana-3.19/Nirvana/Nirvana.cs:line 37
   at CommandLine.Builders.ConsoleAppErrors.Execute(Func`1 executeMethod) in /home/sergey/Nirvana-3.19/CommandLine/Builders/ConsoleAppBuilder.cs:line 162
```

launched by a command:

```
dotnet bin/Release/net6.0/Nirvana.dll \
        -c Data/Cache/GRCh37/Both \
        --sd Data/SupplementaryAnnotation/GRCh37 \
        -r Data/References/Homo_sapiens.GRCh37.Nirvana.dat \
        -i "202556491.vcf.gz" -o "202556491.vcf.gz"
```

version:

```
dotnet ~/Nirvana-3.19/bin/Release/net6.0/Nirvana.dll --version
Nirvana 3.18.1 Cache version: 27, Supplementary annotation version: 66, Reference version: 7
```

**Comment by schreyers** [comment]
@sorgoz did you manage to fix this?

I have a different error but wondered if its a command or setup issue so just looking for other setups that work with the 3.18.1 version

**Comment by sorgoz** [comment]
> @sorgoz did you manage to fix this?
> 
> I have a different error but wondered if its a command or setup issue so just looking for other setups that work with the 3.18.1 version

Actually, I forgot to close this issue - my VCF file was apparently corrupted during transfer and when I redownloaded the VCF all went fine.
