### ISSUE TITLE
Input string was not in a correct format

### ISSUE THREAD

**Issue by AdamuUu** [Illumina/Nirvana#51]
Could you help me with this one?
What I run:
```
dotnet /home/adam/soft/nirvana/Nirvana/bin/Release/netcoreapp2.1/Nirvana.dll \
     --cache /home/adam/Pulpit/S5/covid_anno/Data/Cache/SARS-CoV-2/SARS-CoV \
     --sd /home/adam/Pulpit/S5/covid_anno/Data/SupplementaryAnnotation/SARS-CoV-2 \
     --ref /home/adam/Pulpit/S5/covid_anno/Data/References/SARS-CoV-2.ASM985889v3.dat \
     --in /home/adam/Pulpit/S5/samtools/RNA_IN_RG_bwa.vcf.gz \
     --out /home/adam/Pulpit/S5/samtools/RNA_IN_vars_anno
```
What I get:
```
---------------------------------------------------------------------------
Nirvana                                             (c) 2020 Illumina, Inc.
Stromberg, Roy, Lajugie, Jiang, Li, and Kang                         3.13.0
---------------------------------------------------------------------------

Initialization                                         Time     Positions/s
---------------------------------------------------------------------------
Cache                                               00:00:00.0

ERROR: Input string was not in a correct format.

Stack trace:
   at System.Number.ParseDouble(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Double.Parse(String s)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at MitoHeteroplasmy.MitoHeteroplasmyReader.GetProvider() in /home/adam/soft/nirvana/Nirvana/MitoHeteroplasmy/MitoHeteroplasmyReader.cs:line 42
   at Nirvana.AnnotationResources..ctor(String refSequencePath, String inputCachePrefix, List`1 saDirectoryPaths, List`1 customAnnotations, String customStrTsvPath, Boolean disableRecomposition, Boolean forceMitochondrialAnnotation, Boolean useLegacyVids, PerformanceMetrics metrics) in /home/adam/soft/nirvana/Nirvana/Nirvana/AnnotationResources.cs:line 75
   at Nirvana.Nirvana.GetAnnotationResources() in /home/adam/soft/nirvana/Nirvana/Nirvana/Nirvana.cs:line 52
   at Nirvana.Nirvana.ProgramExecution() in /home/adam/soft/nirvana/Nirvana/Nirvana/Nirvana.cs:line 34
   at CommandLine.Builders.ConsoleAppErrors.Execute(Func`1 executeMethod) in /home/adam/soft/nirvana/Nirvana/CommandLine/Builders/ConsoleAppBuilder.cs:line 162
```

**Comment by MichaelStromberg** [comment]
Hi Adam,

Since I didn't have the VCF that you used, I went ahead and used the [COVID-19 VCF](https://illumina.github.io/NirvanaDocumentation/files/Covid19Mutations.vcf.gz) provided on [our documentation site](https://illumina.github.io/NirvanaDocumentation/introduction/covid19/)

I used the precompiled binaries for both 3.13 and 3.14 and everything worked well. You can find the precompiled binaries for Nirvana 3.14 here: https://github.com/Illumina/Nirvana/releases/tag/v3.14.0 (look in the assets section)

**Comment by AdamuUu** [comment]
Hi Michael,

Thank you so much for help and support!

Best Regards,
Adam





czw., 29 kwi 2021 o 23:13 Michael Strömberg ***@***.***>
napisał(a):
