### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by biodetective** [Illumina/Nirvana#79]
I am running the test command:

dotnet bin/Release/netcoreapp3.1/Nirvana.dll \
     -c Data/Cache/GRCh37/Both \
     --sd Data/SupplementaryAnnotation/GRCh37 \
     -r Data/References/Homo_sapiens.GRCh37.Nirvana.dat \
     -i HiSeq.10000.vcf.gz \
     -o HiSeq.10000

ERROR: Object reference not set to an instance of an object.

---------------------------------------------------------------------------
Nirvana                                             (c) 2022 Illumina, Inc.
Stromberg, Roy, Platzer, Siddiqui, Ouyang, et al                     3.18.0
---------------------------------------------------------------------------

Initialization                                         Time     Positions/s
---------------------------------------------------------------------------
Cache                                               00:00:01.4

ERROR: Object reference not set to an instance of an object.

Stack trace:
   at VariantAnnotation.GenericScore.ScoreIndex.Read(Stream stream, Int32 dataFilePairId) in ~/Nirvana/VariantAnnotation/GenericScore/ScoreIndex.cs:line 154
   at VariantAnnotation.GenericScore.ScoreReader.Read(Stream dataStream, Stream indexStream) in ~/Nirvana/VariantAnnotation/GenericScore/ScoreReader.cs:line 56
   at Nirvana.ProviderUtilities.GetGsaProvider(AnnotationFiles files) in ~/Nirvana/Nirvana/ProviderUtilities.cs:line 87
   at Nirvana.AnnotationResources..ctor(String refSequencePath, String inputCachePrefix, List`1 saDirectoryPaths, List`1 customAnnotations, String customStrTsvPath, Boolean disableRecomposition, Boolean forceMitochondrialAnnotation, Boolean useLegacyVids, PerformanceMetrics metrics) in ~/Nirvana/Nirvana/AnnotationResources.cs:line 69
   at Nirvana.Nirvana.GetAnnotationResources() in ~/Nirvana/Nirvana/Nirvana.cs:line 61
   at Nirvana.Nirvana.ProgramExecution() in ~/Nirvana/Nirvana/Nirvana.cs:line 38
   at CommandLine.Builders.ConsoleAppErrors.Execute(Func`1 executeMethod) in ~/Nirvana/CommandLine/Builders/ConsoleAppBuilder.cs:line 162

Can you help me out? 

Thank you very much!

**Comment by rajatshuvro** [comment]
Sorry about that @biodetective . I am taking a look.

**Comment by rajatshuvro** [comment]
Issue has been fixed in the 3.18.1 release.
